### ISSUE TITLE
[🚫 Bug] TypeError of all properties in ui-test

### ISSUE THREAD

**Issue by anvuong48** [redhat-developer/vscode-extension-tester#1378] opened 2024-06-23 16:27 UTC
### Describe the bug

I was trying to run all ui tests from [helloworld-extester](https://github.com/redhat-developer/vscode-extension-tester/tree/main/examples/helloworld-extester) that is example from vscode-extension-tester. After installing vscode and chromedriver,all ui tests failed with errors e.g "TypeError: Cannot read properties of undefined". For example the first test **activityBar.test.ts**  has TypeError: Cannot read properties of undefined (reading 'ActivityBar'). 

### Steps to reproduce

```Shell
Requirements: 
- node v18.15.0, vscode 1.90.2, OS: windows
- package.json could be found in helloworld-extester project.
1. Clone [helloworld-extester](https://github.com/redhat-developer/vscode-extension-tester/tree/main)
2. cd examples/helloworld-extester
3. create new folder named "test-resources" under helloworld-extester
2. Run the following commands:
`npm install`
`npm run compile`
`extest setup-and-run './out/ui-test/*.test.js'-s .\test-resources\ -c 1.85.0 --code_settings settings.json`
```

### Logs

```Shell
1) Activity Bar Example Tests
       "before all" hook for "Shows explorer view control (container)":
     TypeError: Cannot read properties of undefined (reading 'ActivityBar')
      at new ActivityBar (node_modules\@redhat-developer\page-objects\out\components\activityBar\ActivityBar.js:27:36)
      at Context.<anonymous> (out\ui-test\activityBar.test.js:26:23)
      at process.processImmediate (node:internal/timers:476:21)

  2) Bottom Bar Example Tests
       "before all" hook in "Bottom Bar Example Tests":
     TypeError: Cannot read properties of undefined (reading 'BottomBarPanel')
      at new BottomBarPanel (node_modules\@redhat-developer\page-objects\out\components\bottomBar\BottomBarPanel.js:28:39)
      at Context.<anonymous> (out\ui-test\bottomBar.test.js:50:21)
      at process.processImmediate (node:internal/timers:476:21)

  3) Bottom Bar Example Tests
       "after all" hook in "Bottom Bar Example Tests":
     TypeError: Cannot read properties of undefined (reading 'toggle')
      at Context.<anonymous> (out\ui-test\bottomBar.test.js:56:25)
      at process.processImmediate (node:internal/timers:476:21)

  4) Sample Command palette tests
       using executeCommand:
     TypeError: Cannot read properties of undefined (reading 'Workbench')
      at new Workbench (node_modules\@redhat-developer\page-objects\out\components\workbench\Workbench.js:37:34)
      at Context.<anonymous> (out\ui-test\commands.test.js:24:15)

  5) Sample Command palette tests
       using the command prompt:
     TypeError: Cannot read properties of undefined (reading 'Workbench')
      at new Workbench (node_modules\@redhat-developer\page-objects\out\components\workbench\Workbench.js:37:34)
      at Context.<anonymous> (out\ui-test\commands.test.js:28:30)

  6) Example extension view tests
       "before all" hook for "Check the extension info":
     TypeError: Cannot read properties of undefined (reading 'ActivityBar')
      at new ActivityBar (node_modules\@redhat-developer\page-objects\out\components\activityBar\ActivityBar.js:27:36)
      at Context.<anonymous> (out\ui-test\extensionsView.test.js:31:35)
      at process.processImmediate (node:internal/timers:476:21)
```

### Operating System

Windows 10 Enterprise

### Visual Studio Code

1.90.2

### vscode-extension-tester

8.3.0

### NodeJS

18.15.0

### npm

9.5.0

**Comment by djelinek** [comment] 2024-07-18 10:59
Hello, thank you for your interest in ExTester. The example project was updated and I am not able to reproduce the described behaviour.

May I ask you, can you please try again locally with latest changes and let me know?

Thank you.

**Comment by djelinek** [comment] 2024-07-18 11:00
and also please keep in mind that in steps to reproduce you are using `-c 1.85.0`. That version is not directly supported and it is not tested any more.

**Comment by djelinek** [comment] 2024-08-21 19:51
closing, feel free to reopen or just continue in the thread here in case of more questions.

**Closed by djelinek** 2024-08-21 19:51 UTC
Labels: bug
