### ISSUE TITLE
[🚫 Bug] Terminal view execute command not working 

### ISSUE THREAD

**Issue by sang2770** [redhat-developer/vscode-extension-tester#1364] opened 2024-06-14 09:33 UTC
### Describe the bug

Terminal view execute command not working  
when execute command then Terminal only create new line and command not show
![image](https://github.com/redhat-developer/vscode-extension-tester/assets/72650632/bc11053d-eb9b-4bcb-aec7-897707a66e60)

### Steps to reproduce

```Shell
Testcase: it("Terminal works", async function () {
      this.timeout(100000);
      assert.ok(await terminalView.isDisplayed());   
      console.log("terminalView", await terminalView.getCurrentChannel());
      await waitTime(2000);
      await terminalView.executeCommand("ls");
      // const text = await terminalView.getText();
      // console.log("text", text);
      
      await waitTime(10000);
    });
```

### Logs

```Shell
Test no error
```

### Operating System

Window 10

### Visual Studio Code

1.89.1

### vscode-extension-tester

8.2.0

### NodeJS

20.14.0

### npm

10.7.0

**Comment by djelinek** [comment] 2024-07-18 13:13
Hello, thank you for your issue. Unfortunately I was not able to reproduce. I did tried modify tests to execute `ls` and it seems to work just fine.

![Image](https://github.com/user-attachments/assets/06566f85-5e29-4efc-be9b-d239f16c5be8)

You can see code below

```typescript
const terminal = await panel.openTerminalView();
await new Promise((res) => setTimeout(res, 2_000));

await terminal.executeCommand('ls', 5_000);
```

Could you please try again with added timeout into `executeCommand` method?

**Comment by djelinek** [comment] 2024-08-21 19:49
closing, feel free to reopen or just continue in the thread here in case of more questions.

**Closed by djelinek** 2024-08-21 19:49 UTC
Labels: bug

**Comment by neochief** [comment] 2024-10-24 00:09
I had the same issue when I forgot to switch my keyboard layout from Russian to English before the test. The command was supposed to be typed in English, but I guess selenium couldn't figure out what keys to send on the current russian layout.
