### ISSUE TITLE
openResources does nothing when run under Docker

### ISSUE THREAD

**Issue by PieterOlivier** [redhat-developer/vscode-extension-tester#506] opened 2022-09-23 12:59 UTC
I have run into an issue where 'openResources' works fine when testing under Windows and Linux, but when run under Docker (using xfvb) 'openResources' does nothing.

I have created a small project that demonstrates the issue.  When this project resides in C:\bugs\mintest, the steps required to reproduce the issue under Docker (on Windows, also tested on Ubuntu) are:
```
winpty docker run --rm -it -v "C:\\bugs\mintest:/app" node:16-bullseye bash

cd app
apt-get update
apt-get install xvfb libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libgbm1 libnss3 libasound2
su - node
cd /app
npm ci
npm run compile
xvfb-run npm run ui-test
```
The test creates a file 'screenshot.png' in the project dir. The problem is that this screenshot does not show an open 'test.txt' file.

When the same test is run under Windows, the screenshot does show an open 'test.txt' file.
Note that src/ui-test/openFile-test.ts contains the variable 'baseDir' that needs to be changed based on the actual location of project.

The complete test project can be found here:
[mintest.tar.gz](https://github.com/redhat-developer/vscode-extension-tester/files/9633112/mintest.tar.gz)

I have added two screenshots to show the problem. The first screenshot is taken by running the test on a Windows machine.
The second screenshot was taken by running the test in Docker. In the Docker variant 'openResources' did not open the text file.

![windows-screenshot](https://user-images.githubusercontent.com/103408614/192273999-b2899409-d97c-4a09-9738-4bd68caeb818.png)

![docker-screenshot](https://user-images.githubusercontent.com/103408614/192277120-54d656e3-d2c6-4818-8aa6-5c3460fef790.png)

**Comment by DavyLandman** [comment] 2022-09-27 07:25
I've also run this code.

Observations:
1. docker on windows or linux both fail.
2. other docker containers (debian/ubuntu/archlinux) run into the same issue, not opening up the file.
3. a fresh ubuntu vps: _it works._

So it should be possible to have this run using xvfb, but something special with regards to if xvfb is inside a docker container?

**Comment by PieterOlivier** [comment] 2022-10-07 06:15
I have tried the approach of @YuggothFungi but it only worked intermittently.
To get it to work at all I had to get dbus up and running in Docker container, and I had to add the "--disable-gpu" option after the "--no-sandbox" option to get vscode to run using xvfb.
But even then, most of the time the initial vscode instance seems to die shortly after starting the commandline version to open a file.

But after studying the vscode-extension-tester API and examples some more, I came up with another (more elegant) approach that did work. Just use the "File -> Open File..." menu and then use the resulting InputBox to actually open the file:
`  
async openEditor(file: string) {
    const titleBar = new TitleBar();
    const item = await titleBar.getItem('File');
    const fileMenu = await item!.select();
    const openItem = await fileMenu.getItem("Open File...");
    await openItem!.select();

    const input = await InputBox.create();
    await input.setText(this.workspaceDir + file);
    await input.confirm();
  }
`
 This works perfectly every time.

**Comment by DavyLandman** [comment] 2022-10-07 07:10
So this points to an issue with `openResource`?

**Comment by c3-kaspesi** [comment] 2022-10-13 20:25
I am also seeing this user in my docker container (Red hat 8) running tests with `xvfb-run`

**Comment by c3-kaspesi** [comment] 2022-10-13 20:44
@PieterOlivier Has this ever been working for you / is a regression that would work with a previous version?

**Comment by PieterOlivier** [comment] 2022-10-17 11:17
It has never worked for me (under docker), but in all fairness it is a recent project so I have no experience with earlier versions.

**Comment by djelinek** [comment] 2023-06-09 13:38
Closing - no issue activity for a long time. Feel free to reopen if needed.

**Closed by djelinek** 2023-06-09 13:38 UTC
Labels: bug

**Comment by djelinek** [comment] 2023-06-12 11:08
> @djelinek I think the people that run into it have been using the work-around. Would you like us to re-run the original example posted in the issue to know if this is still a bug?

Hello @DavyLandman it would help me because I have no capacity currently to reproduce on my local. Thanks.

**Comment by lanshunfang** [comment] 2023-09-17 04:34
This happens to me. I consider it a critical issue as it blocks ci/cd, most of which demands running tests in docker.

**Comment by bmingles** [comment] 2025-02-28 21:06
I'm still experiencing this issue as of ^8.13.0. The [workaround](https://github.com/redhat-developer/vscode-extension-tester/issues/506#issuecomment-1271156702) still works though.

**Comment by bmingles** [comment] 2025-03-11 20:59
I ran into issues with the workaround not working multiple times. Input seemed to get stuck open for some reason. Using the quick open instead worked for me for files:

```typescript
await new Workbench().executeCommand('workbench.action.quickOpen');

const input = await InputBox.create();
await input.setText(filePath);
await input.confirm();
```
