### ISSUE TITLE
TreeItem.findChildItem Finds the Wrong Element

### ISSUE THREAD

**Issue by owenfarrell** [redhat-developer/vscode-extension-tester#145] opened 2020-07-22 21:24 UTC
I've been working on implementing automated tests for a VSCode extension I publish. My work-in-progress can be found here:

https://github.com/owenfarrell/vscode-vault/tree/ui-tests

As part of the test suite, `vscode-extension-tester` interacts with 2 `TreeItem` instances that have the same children:
* Localhost - Native
* Localhost - Username & Password

When running the tests, which leverage `vscode-extension-tester`, there is a [whole suite](https://github.com/owenfarrell/vscode-vault/blob/ui-tests/test/browse/kv1.ts#L111-L151) that is supposed to interact with children of the `Localhost - Username & Password`. But when you watch the tests run, all interactions are with the wrong parent node. So all the tests pass because the children are identical, but if you watch the tests, the interactions are all wrong.

If you want to run the test for yourself, the contributions guidelines outline the required steps (Docker + npm).

**Comment by jrichter1** [comment] 2020-07-23 06:46
Thanks for the issue and all the useful info, @owenfarrell 

Item indexing in this case is indeed broken, `findChildren` will always take the top most item with the given name and search for its children. I guess I didn't know what I was doing back when I wrote this, so let me fix that now at least :)

**Comment by owenfarrell** [comment] 2020-07-23 14:00
@jrichter1 - Thanks for acknowledgement!

I'm happy to take a crack at the PR, I'm just struggling to find where to start. The logic in `TreeItem.findChildItem` looks right to me. Are you saying the issue is really in `CustomTreeSection.findItem` and/or `DefaultTreeSection.findItem?

**Comment by jrichter1** [comment] 2020-07-24 07:53
This might be a bit more complex change. I have looked over the code and I'd like to take this as an opportunity to also clean it up a bit, if you don't mind.

**Comment by owenfarrell** [comment] 2020-07-24 13:52
Works for me. Let me know if I can chip in at all (not sure if you have a punch list in your head or if this is more of a freeform effort).

**Comment by yannickowow** [comment] 2020-08-06 11:42
Hi, 
Sorry if I miss the main point of this post. 
I have an issue that can be related to this one as well. If I call 'section.openItem('item-name'), it may return an array of ViewItem containing childrens, isn't it ?
In my case, it returns an empty array if it exists, and undefined otherwise.
I checked this folder and it should have files and folders...

Thanks in advance

**Comment by jrichter1** [comment] 2020-08-06 12:27
@yannickowow the return type for `section.openItem('item-name')` is `Promise<TreeItem[]>`. If the item you want to open doesn't exist, it throws an error. 
 
I'm experiencing the `it works for me` scenario here, some debugging might be in order. One thing that comes to mind is to make sure all the asynchronous calls, including this one, are properly synchronized. In other words, make sure the promises are either awaited, or properly chained if not using async/await. Something like
```typescript
let children = await section.openItem('item-name');
```
If it doesn't help, more info might be needed (the test code, the folder structure if possible).

And BTW the original issue should be resolved already, I just forgot to close this :)

**Comment by yannickowow** [comment] 2020-08-06 13:53
Thanks for your fast reply and sorry for the inconvenience.
My use case here is that I copy an empty folder using your own command API `Extest: Add Folder to Workspace` using executeCommand() and I test my own plugin to copy a template.
After that, I want to check if my tree is completed, so I ran this code:
```javascript
const item = await (await content.getSection('Untitled (Workspace)'))
            .openItem('ws-folder') as ViewItem[];
```
I expect item to have content of my folder 'ws-folder', including subfolders and files.
It returns an empty array.
If I set a wrong name (lets say : 'non-existent'), it returns an error.

**Comment by jrichter1** [comment] 2020-08-07 08:09
So far I have not been able to replicate the problem. This is what the test case looks like:
```typescript
it('openItem returns folders subitems', async () => {
  await new Workbench().executeCommand('extest open folder');
  const input = await InputBox.create();
  await input.setText(path.resolve('path', 'to', 'ws-folder'));
  await input.confirm();
    
  const view = await new ActivityBar().getViewControl('Explorer').openView();
  const content = view.getContent();

  const items = await (await content.getSection('Untitled (Workspace)'))
     .openItem('ws-folder') as TreeItem[];

  console.log(await Promise.all(items.map(item => item.getLabel())));

  expect(items.length).gt(0);
});
```
I'm consistently getting the correct list of child items from the folder. Let me know if there is something you've done in a different fashion. I'd also recommend trying to step through your test with a debugger (example configuration is [here](https://github.com/redhat-developer/vscode-extension-tester/wiki/Debugging-Tests))

**Comment by yannickowow** [comment] 2020-08-07 08:38
Hi, thanks for your reply.
My test case currently looks like : 
```javascript
// Open folder 
        before(async function () {
            this.timeout(10000);
            await ws.executeCommand(EXTEST_OPEN_FOLDER);
            const input = await InputBox.create();
            await input.setText(resolve(__dirname, '..', '..', 'resources', 'ws-folder'));
            await input.confirm();
        });
```
My folder opens correctly as far as I know.
I use your test case here to see if I was doing something wrong : 
```javascript
        it('Verifies that ws-folder is empty', async function () {
            this.timeout(100000);
            const view = await new ActivityBar().getViewControl('Explorer').openView();
            const content = view.getContent();
            const items = await (await content.getSection('Untitled (Workspace)'))
            .openItem('ws-folder') as TreeItem[];
            console.log(await Promise.all(items.map(item => item.getLabel())));
            expect(items.length).gt(0);
        });
```
Here, it should be greater than zero because my tree has multiple folders :  `.vscode`, `bin`, `src`, and a  `Makefile`

I use current configuration in my launch.json
```jsonc
		{
			"name": "UI Tests",
			"type": "node",
			"request": "launch",
			"program": "${workspaceFolder}/node_modules/vscode-extension-tester/out/cli.js",
			"args": [
				"setup-and-run",
				"${workspaceFolder}/out/ui-tests/*.js",
				"-o",
				"resources/test-settings.json"
			],
			"console": "integratedTerminal",
			"internalConsoleOptions": "neverOpen",
		}
```
If I use your own configuration, I have this error
```sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

**Comment by owenfarrell** [comment] 2020-08-23 17:57
@jrichter1 - I know this thread went in a very different direction, but I just wanted to check in on the original ask.

I saw your commit (1e1c29d6715f269731dfd74cd8883cdf55b6c25e) reference an update to `TreeItem`s, but I don't see a tagged release of that work yet.

Is there anything I can help with to get your updates over the finish line?

**Comment by jrichter1** [comment] 2020-08-24 07:08
@owenfarrell the patch has been live on npmjs for a while. It didn't involve the main module, so it should get picked up when you run `npm install` or `npm update`.

As for the tags, I'm still unsure if every patch of every package deserves its own tag (there are four packages in this repo after all).

**Comment by owenfarrell** [comment] 2020-08-26 19:22
@jrichter1 - Circling back on this...

Personally, I didn't catch the update because I don't have an explicit dependency on `monaco-page-objects`. So doing a clean install didn't help as the (transitive) dependency is pinned based on the 3.1.0 release.

When I pin `monaco-page-objects` to 1.2.2 in my manifest, or upgrade `vscode-extension-tester` to 3.2.0, I'm hitting a new issue: `TreeItem.getChildren` always returns an empty array.

I see there were some other modifications as part of https://github.com/redhat-developer/vscode-extension-tester/commit/1e1c29d6715f269731dfd74cd8883cdf55b6c25e. Is that intended to be a backwards-breaking change?

**Comment by jrichter1** [comment] 2020-08-27 07:11
@owenfarrell the transitive dependency is defined as `"vscode-extension-tester-locators": "^1.44.0"`, so npm should pull the latest minor of 1.x without you having to pin it into your own manifest. That being said, `package-lock.json` usually pins a specific version of transitive dependencies available at the time it was created. Deleting it usually lets `npm install` pull all the newer packages.

I think I might have finally found the root of the empty array problem, turns out I'm bad at publishing packages. Sorry it took so long to realize, @yannickowow .

**Comment by jrichter1** [comment] 2020-08-27 07:21
I managed to find a single file that got published in a wrong revision for some reason. I've reuploaded one of the packages and the problem should be fixed now. 

Please make sure all the latest transitive dependencies are pulled, worst case you might need to delete `package-lock.json` and `node-modules` to redownload everything.

**Comment by owenfarrell** [comment] 2020-09-03 21:43
@jrichter1 - I'm not sure how to describe the new behavior I'm seeing, but here's my best attempt....

After upgrading to `3.2.0` (if you need more specifics from my package-lock, let me know), my handle to existing `extest.TreeItem` seems to change on me.

For example, I have a tree view with:
* A top-level `TreeItem` with the label `Localhost - Native`
* 3 children under that top-level `TreeItem` (labeled `cubbyhole/`, `kv/`, `secret/`)

When I call `serverTreeItem = viewSection.findItem('Localhost - Native', 1)`, everything is great. I get a handle to the correct `TreeItem`.

When I call `parentTreeItem = serverTreeItem.findChildItem('cubbyhole/')`, I get a handle to the first child. Again, all good!

When I expand the `parentTreeItem`, which may or may no add children behind the scenes, the handle to `parentTreeItem` "drifts".... it suddenly points to the `serverTreeItem` instead. I've checked the label/children/etc. and it's definitely pointing to the wrong element in the tree.

From there on, my tests are hosed because I'm not connected to the right point of the hierarchy in the tree.

Is there some kind of utility/refresh function that I should be calling if/when new `TreeItem` instances are added to a `TreeView`?

**Comment by jrichter1** [comment] 2020-09-04 08:38
That's nasty. Normally, when a folder is opened, a new DOM element should spawn for each child item. In some cases though, the parent item just gets updated with attributes of the first child item and then a new element is spawned for the parent instead.
And since the page objects are bound to their respective elements, it effectively means the page object will now reference a different file/folder (while still being the same element). 

I have no idea why it happens (I'd like to blame new versions of vscode). I'll see if it is possible to mitigate the effect though.

**Comment by jrichter1** [comment] 2020-09-04 10:37
@owenfarrell The issue seems to be happening when expanding the first child of the root folder. For some reason the underlying element for the subfolder switches with the element representing the first visible file in the tree.

WebDriver reports the same identifier, meaning it should be the same element, but then all the attributes are different. There is some black magic happening is the browser or webdriver (or combination of the two). 

Worst thing is, it seems impossible to make a universal fix for this, since the page objects rely on the DOM elements being statically bound to them. When the issue can be reproduced by calling something as simple as `item.click()`, one can't reassign the instance from within itself. Only chance is if there is a way to circumvent this behaviour all together.

While I'm trying to come up with some solution, I suggest working around the issue. Whenever this happens, you can get the proper element by searching for the given item again. I know it's inconvenient, but that's the best I have right now.

**Closed** 2023-06-17 01:59 UTC
Labels: no-issue-activity
