### ISSUE TITLE
Input.getMessage() appears to enter text into the input thereby triggering the validateInput function

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#91] opened 2020-04-09 17:49 UTC
My extension creates at a certain point an InputBox which properties I am trying to verify via vscode-extension-tester. However I am having trouble using the `getMessage()` function as described in the Wiki: https://github.com/redhat-developer/vscode-extension-tester/wiki/Input#quick-input-message

It appears that the `getMessage()` focuses the inputBox and thereby triggers the `validateInput` function. In my case an empty input is unfortunately invalid, which immediately causes VSCode to display an error message in the input. `getMessage()` then returns this error message instead of the string passed via the `prompt` entry for `showInputBox`.

**Comment by jrichter1** [comment] 2020-04-14 13:47
I tried creating a small reproducer like so:
 - create a command to show input box with validation for empty value
 - call the command and obtain the input box reference
 - call `getMessage`

The above does not trigger validation, not even after repeated attempts. To actually trigger validation I had to either:
 - attempt to confirm the empty box right away
 - use `setText` to type something in and then call `clear`
 - click away from the input box (given `ignoreFocusOut` is set to `true`)

Do you perform some text manipulation in the input box before calling `getMessage` (or any of the above for that matter)?
The validation triggers about half a second after the text has been changed. If something did change, the message might not have changed until the next call.

**Comment by dcermak** [comment] 2020-04-24 20:50
> I tried creating a small reproducer like so:
> 
>     * create a command to show input box with validation for empty value
> 
>     * call the command and obtain the input box reference
> 
>     * call `getMessage`
> 
> 
> The above does not trigger validation, not even after repeated attempts. To actually trigger validation I had to either:
> 
>     * attempt to confirm the empty box right away
> 
>     * use `setText` to type something in and then call `clear`
> 
>     * click away from the input box (given `ignoreFocusOut` is set to `true`)
> 
> 
> Do you perform some text manipulation in the input box before calling `getMessage` (or any of the above for that matter)?

No, not really. In that specific test I am just doing this:
``` typescript
await startCommand();
const urlInput = await InputBox.create();
await urlInput
  .getPlaceHolder()
  .should.eventually.deep.equal("https://my-url.org");
await urlInput
  .getMessage()
  .should.eventually.deep.equal(
    "Enter an URL"
  );
```
the `getPlaceHolder()` check succeeds, the `getMessage()` one does not (swapping them does not help).

What could make the difference is `startCommand()`, this function executes a command that opens a quick pick and one of these is selected, then quick pick is confirmed:
``` typescript
const startCommand = async (): Promise<void> => {
await new Workbench().executeCommand(
  "COMMAND NAME HERE"
);

const input = await InputBox.create();
await input.selectQuickPick("other (custom)");
await input.confirm();
await input.getDriver().sleep(100);
}
```

I've stripped this down a bit and found out that the inputBox actually starts out in an error state (i.e. the following test "succeeds", although it shouldn't):
``` typescript
await startCommand();
const urlInput = await InputBox.create();
await urlInput.hasError().should.eventually.equal(true);
```

No idea what is going on here, could it be some weird interaction as I am creating multiple inputs after each other?

**Comment by jrichter1** [comment] 2020-04-27 08:38
I'm struggling to pinpoint the cause here, just a couple of ideas.

Make sure the first input is closed before looking for the second one (maybe it is still picking up the first one).

When all fails, try [debugging](https://github.com/redhat-developer/vscode-extension-tester/wiki/Debugging-Tests) the tests.

**Comment by djelinek** [comment] 2023-06-09 12:59
Closing - no issue activity for a long time. Feel free to reopen if needed.

**Closed by djelinek** 2023-06-09 12:59 UTC
